# Generated by Django 5.2.11 on 2026-02-07 20:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(help_text='Формат: +79991234567', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+79991234567'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('attraction_channel', models.CharField(choices=[('website', 'Сайт'), ('recommendation', 'Рекомендация'), ('advertising', 'Реклама'), ('walk_in', 'Проходящий мимо'), ('other', 'Другое')], default='website', max_length=50, verbose_name='Канал привлечения')),
                ('consent_sms', models.BooleanField(default=False, verbose_name='Согласие на SMS')),
                ('consent_email', models.BooleanField(default=False, verbose_name='Согласие на Email')),
                ('consent_phone', models.BooleanField(default=True, verbose_name='Согласие на звонки')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='core_client_phone_e857f7_idx'), models.Index(fields=['last_name', 'first_name'], name='core_client_last_na_9b60fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Год выпуска')),
                ('vin', models.CharField(blank=True, help_text='17 символов', max_length=17, null=True, unique=True, verbose_name='VIN номер')),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Госномер')),
                ('mileage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пробег (км)')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client'], name='core_vehicl_client__978040_idx'), models.Index(fields=['vin'], name='core_vehicl_vin_167573_idx'), models.Index(fields=['license_plate'], name='core_vehicl_license_026ac1_idx')],
            },
        ),
    ]
