# Generated by Django 6.0.1 on 2026-02-16 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                error_messages={"unique": "Клиент с таким телефоном уже существует."},
                help_text="Формат: +79991234567",
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Телефон должен быть в формате: '+79991234567'",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(
                blank=True,
                error_messages={
                    "unique": "Автомобиль с таким VIN номером уже существует."
                },
                help_text="17 символов",
                max_length=17,
                null=True,
                unique=True,
                verbose_name="VIN номер",
            ),
        ),
    ]
