# Generated by Django 5.2.11 on 2026-03-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_client_phone_alter_vehicle_vin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Фамилия"
            ),
        ),
    ]
