# Generated by Django 5.2.11 on 2026-03-11 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_client_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_confirmation", "Ожидает подтверждения email"),
                            ("confirmed", "Подтверждена"),
                            ("in_progress", "В работе"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="pending_confirmation",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Описание проблемы / желаемая услуга",
                    ),
                ),
                (
                    "vehicle_passport_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Паспорт ТС №",
                    ),
                ),
                (
                    "vehicle_engine_volume",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Объём двигателя, куб.см",
                    ),
                ),
                (
                    "vehicle_engine_power",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Мощность двигателя, л.с.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Заметки мастера"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на запись",
                "verbose_name_plural": "Заявки на запись",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="client",
            name="consent_email",
        ),
        migrations.RemoveField(
            model_name="client",
            name="consent_phone",
        ),
        migrations.RemoveField(
            model_name="client",
            name="consent_sms",
        ),
        migrations.AddField(
            model_name="client",
            name="auth_code",
            field=models.CharField(
                blank=True, default="", max_length=6, verbose_name="Код авторизации"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="auth_code_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Код создан"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="consent_personal_data",
            field=models.BooleanField(
                default=False, verbose_name="Согласие на обработку ПДн"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Email подтверждён"),
        ),
        migrations.AddField(
            model_name="client",
            name="verification_token",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="Токен подтверждения",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="verification_token_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Токен создан"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email"], name="core_client_email_9bd669_idx"),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_requests",
                to="core.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_requests",
                to="core.vehicle",
                verbose_name="Автомобиль",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingrequest",
            index=models.Index(
                fields=["client"], name="core_bookin_client__190ba1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingrequest",
            index=models.Index(fields=["status"], name="core_bookin_status_52b65b_idx"),
        ),
    ]
