# Generated by Django 5.2.11 on 2026-03-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_bookingrequest_remove_client_consent_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="auth_code_failed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последний неверный ввод"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="auth_code_failed_attempts",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Неверных попыток кода"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="auth_code_last_send_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последняя отправка кода"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="auth_code_send_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Отправок кода"),
        ),
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Деактивированный клиент не может войти.",
                verbose_name="Активен",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(
                blank=True,
                help_text="17 символов",
                max_length=17,
                null=True,
                verbose_name="VIN номер",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["is_active", "email"], name="core_client_is_acti_28be91_idx"
            ),
        ),
    ]
