# Generated by Django 5.2.11 on 2026-03-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_client_is_active_rate_limiting_vehicle_vin_not_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingrequest",
            name="vehicle_engine_volume",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="Объём двигателя, л"
            ),
        ),
    ]
